# Generated by Django 3.0.8 on 2020-07-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='views',
        ),
        migrations.AlterOrderWithRespectTo(
            name='page',
            order_with_respect_to='category',
        ),
    ]
